"""Add many-to-many relationship between posts and tags

Revision ID: 87c033e010af
Revises: 97330348131a
Create Date: 2025-10-28 21:46:15.146716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c033e010af'
down_revision = '97330348131a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the post_tags association table
    op.create_table('post_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_tags_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_post_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_tags')),
    sa.UniqueConstraint('post_id', 'tag_id', name='unique_post_tag')
    )

    # Migrate existing data from posts.tag_id to post_tags table
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT id, tag_id FROM posts WHERE tag_id IS NOT NULL"))
    for post_id, tag_id in result:
        conn.execute(
            sa.text("INSERT INTO post_tags (post_id, tag_id) VALUES (:post_id, :tag_id)"),
            {"post_id": post_id, "tag_id": tag_id}
        )

    # Now drop the old tag_id column
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_tag_id_tags', type_='foreignkey')
        batch_op.drop_column('tag_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_posts_tag_id_tags', 'tags', ['tag_id'], ['id'])

    op.drop_table('post_tags')
    # ### end Alembic commands ###
