"""revert to single tag per post

Revision ID: a7d9226ed230
Revises: 87c033e010af
Create Date: 2025-10-29 01:19:56.191608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d9226ed230'
down_revision = '87c033e010af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_tag_id_tags'), 'tags', ['tag_id'], ['id'], ondelete='SET NULL')

    # Migrate data from post_tags to posts.tag_id (take first tag only)
    conn = op.get_bind()
    # For each post, get the first tag from post_tags and set it as tag_id
    conn.execute(sa.text("""
        UPDATE posts
        SET tag_id = (
            SELECT tag_id
            FROM post_tags
            WHERE post_tags.post_id = posts.id
            LIMIT 1
        )
    """))

    # Drop the post_tags table
    op.drop_table('post_tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_tag_id_tags'), type_='foreignkey')
        batch_op.drop_column('tag_id')

    # ### end Alembic commands ###
