"""add status, tag_id, and image to posts

Revision ID: fe90c3c751ba
Revises: d9b447916c28
Create Date: 2025-10-25 14:14:26.549827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe90c3c751ba'
down_revision = 'd9b447916c28'
branch_labels = None
depends_on = None


def upgrade():
    # Delete existing posts to avoid migration conflicts
    # (Since this is a development database, it's safe to clear data)
    op.execute('DELETE FROM posts')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('NATURA', 'URBAN', 'RURAL', name='poststatus'), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_posts_tag_id_tags'), 'tags', ['tag_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_tag_id_tags'), type_='foreignkey')
        batch_op.drop_column('tag_id')
        batch_op.drop_column('image')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
